### ISSUE TITLE
Compatibility with Carry On mod

### ISSUE THREAD

**Issue by vpontin** [kenijey/realfirstpersonrender#4]
Hi! Can you add support for [Carry On](https://minecraft.curseforge.com/projects/carry-on)? Using both mods when i carry anything both the standard 1st person and your custom 1st person are rendered simultaneously.

The mod Github repository: https://github.com/Tschipp/CarryOn
Author: @Tschipp

Thanks in advance!

**Comment by Tschipp** [comment]
Hey! Thanks for notifying the mod author of Real First Person Render. However, The fix needed to be done on my end, which I already have. You can expect to see it in the next release!

**Comment by vpontin** [comment]
Thanks a lot @Tschipp !!
